name: "terraform"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  tf_version: "latest"
  tf_working_dir: "."
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_READ_ALL_PROJECTS }}
  GITHUB_TOKEN: ${{ secrets.ENGINEERING_GITHUB_PERSONAL_ACCESS_TOKEN }}

jobs:
  terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          token: ${{ secrets.ENGINEERING_GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: cd example/create-env-cluster-topics/;terraform fmt

      - name: Terraform Init
        id: init
        run: cd example/create-env-cluster-topics/;terraform init

      - name: Terraform Validate
        id: validate
        run: cd example/create-env-cluster-topics/;terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: cd example/create-env-cluster-topics/;terraform plan -no-color
        continue-on-error: true
